baseURL = "/"
languageCode = "en-us"
title = "Plotkai Interactive"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@plotkai"

  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false

  addFrame = false
  addDot = true

  highlightColor = '#7b16ff'
